# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://nasa-butterfly.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title      : Butterfly
email      : cgentemann@faralloninstitute.org #this is also the email contact forms will go to
description: "NASA Earth Venture Mission - 3 Proposal"
author     : Chelle Gentemann
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme
